name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and push Docker image to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # Login to Heroku Container Registry
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
        
        # Build the Docker image
        docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
        
        # Push the image to Heroku Container Registry
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        
        # Release the image (using Heroku API directly)
        curl -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})'",
                "quantity": 1
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
        
    - name: Deployment Status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🚀 Your Streamlit app should be available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
