name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: true
        docker_heroku_process_type: web
        
    - name: Deployment Status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🚀 Your Streamlit app should be available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
