name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build, Push and Deploy to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        # The email address associated with your Heroku account
        email: ${{ secrets.HEROKU_EMAIL }}
        
        # Heroku API key associated with provided user's email
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        
        # Name of the heroku app to which the deployment is done
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        
        # (Optional, default: "./Dockerfile")
        # Dockerfile directory.
        # For example, if you have a Dockerfile in the root of your project, leave it as "./"
        # If you have a Dockerfile in a sub directory, change it to something like "./sub_directory"
        dockerfile_directory: "./"
        
        # (Optional, default: "Dockerfile")
        # Dockerfile name.
        dockerfile_name: "Dockerfile"
        
        # (Optional, default: "")
        # Additional options of docker build command
        docker_options: "--no-cache"
        
        # (Optional, default: "web")
        # Select the process type for which you want the docker container to be used.
        # By default, this argument is set to "web"
        # For more information look at https://devcenter.heroku.com/articles/process-model
        process_type: "web"
        
    - name: Deployment Status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🚀 Your Streamlit app should be available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
